---
framework: 'jest'
postMerge:
  pattern:
    - './test/integration/create-react-app/index.test.js'
preMerge:
  pattern:
    - './test/integration/create-react-app/index.test.js'
preRun:
  - npm install
postRun:
  - node --version
version: 2.1
