---
framework: jest
preRun:
  command:
    - npm install
preMerge:
  pattern:
    - './test/integration/create-react-app/index.test.js'
postMerge:
  pattern:
    - './test/integration/create-react-app/index.test.js'
postRun:
  command:
    - node --version
version: 1.0
